#!/bin/sh
sudo apt-get update
sudo apt-get install gdebi
sudo apt-get install firefox
sudo apt-get install python2.7
sudo apt-get install python-pip
pip install browsermob-proxy
pip install selenium
pip install unzip
sudo apt-get -y install openjdk-8-jre-headless
sudo cp geckodriver /usr/bin
sudo apt-get install xvfb
sudo apt-get install xserver-xorg-core
pip install pyvirtualdisplay