#!/bin/sh 
apt-get update -y
apt-get install -y firefox
apt-get install -y  python2.7
apt-get install -y python-pip
apt-get install -y openjdk-8-jre-headless
apt-get install -y xvfb
apt-get install -y xserver-xorg-core
pip install browsermob-proxy
pip install selenium
apt-get install unzip
pip install pyvirtualdisplay
unzip browsermob-proxy-2.1.4-bin.zip
cp geckodriver /usr/bin
chmod a+x /usr/bin/geckodriver
